version: '3.4'

services:
  app:
    image: table-app
    build:
      context: .
      dockerfile: ./Docker
    restart: always
    environment:
      NODE_ENV: production
    env_file: .env
    ports:
      - 3000:5000
    depends_on:
      - "db-table"
    # command: sh -c "./wait-for-it.sh db:5432 && npx prisma migrate deploy && npm start"
    command: "sleep 3 && npx prisma migrate deploy && npm start"

  db-table:
    env_file:
      - .env
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: user12345
      POSTGRES_DB: table_db
    ports:
       - "5434:5434"
    volumes:
       - "db-data:/var/lib/postgresql/data:rw"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
  
volumes:
    db-data: {}
