version: "3.1"

services:
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx-local/static:/usr/share/nginx/html
  #     - ./nginx-local/templates:/etc/nginx/templates
  #   ports:
  #     - "80:80"
  #   environment:
  #     - NGINX_PORT=80
  #     - PROXY_URL_API=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:4000
  #     - PROXY_URL_NEXT=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3000

  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env #Here we are using the already existing .env.local file
    ports:
      - "5432:5432"
    networks:
      - cars-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - cars-net

volumes:
  data:

networks:
  cars-net:
    name: cars-net