import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { Login } from '../src/component/Login'




const  Admin: NextPage = () => {

    return (
      <>
        <Head>
          <title>APKOHT STATISTIC Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Login />
        
    
      </>
    )
  }
  
  export default Admin
  