import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'

import { RegComponent } from '../src/component/admin/Reg'

const  regAdmin: NextPage = () => {
    return (
      <>
        <Head>
          <title>APKOHT STATISTIC Registration</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <RegComponent />
     
      </>
    )
  }
  
  export default regAdmin
  